# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html for more information

[sncast.default] # Define a profile name
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_7/mLHskI2HsCQrodimPkMEefxe5r8XSLhy" # Url of the RPC provider
# accounts_file = "../account-file"                      # Path to the file with the account data
account = "coiton" # Account from `accounts_file` or default account file that will be used for the transactions
# keystore = "~/keystore"                                # Path to the keystore file
# wait_params = { timeout = 500, retry_interval = 10 }   # Wait for submitted transaction parameters
# block_explorer = "StarkScan"                           # Block explorer service used to display links to transaction details
# 0x0789c6bb8cb6d1940dac78907c86dfc1c336bf2a1d3532cb0d1e6e571391820e
